### PR TITLE
Implement lsw

### PR DESCRIPTION
**Pull request by panicbit**

### CODE REVIEW

**Comment by sector-f** [comment]
I notice that this implementation of `lsw` has a noticeable lag compared to the original--`time` reports it takes 0.150 seconds. The original takes 0.002 seconds. Does this have something to do with using Docopt, or is it something else?

**Comment by panicbit** [comment]
Try again using --release

Adam notifications@github.com schrieb am So., 3. Apr. 2016 16:37:

**Comment by panicbit** [comment]
And yeah, docopt is probably the biggest time sink in lsw.

Mike Duenbostell m.duenbostell@gmail.com schrieb am So., 3. Apr. 2016
16:38:

**Comment by sector-f** [comment]
Well, that does get it down to 0.008. Good enough!

**Comment by panicbit** [comment]
Yeah, we can still get rid of docopt at some point anyway, but for now I
wanted this to be done :)

Adam notifications@github.com schrieb am So., 3. Apr. 2016 16:42:

**Pull request merged**
